# Yocto layer configuration: meta-portfolio

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "portfolio"
BBFILE_PATTERN_portfolio := "^${LAYERDIR}/"
BBFILE_PRIORITY_portfolio = "8"

LAYERSERIES_COMPAT_portfolio = "kirkstone langdale mickledore nanbield scarthgap"
